# Simple workflow for deploying static content to GitHub Pages
name: Building

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout it the source code
        uses: actions/checkout@v6

      - name: Setting up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Installing dependencies
        run: npm ci

      - name: Running tests
        run: npm test
